config/routes.rb
Rails.application.routes.draw do
  resources :boxes, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :show]
  get '/', to: 'welcome#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/sell_cards', to: 'users#select_cards'
  post '/sell_cards', to: 'users#sell_cards'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_cards 
    has_many :cards, through: :user_cards
    has_secure_password
    validates :name, presence: true
    validates :name, uniqueness: true

    def self.top_five_users
        self.order(points: :desc).first(5)
    end

    def num_of_cards
        self.cards.count
    end





    #################     leaderboard methods     #############################
    def self.oldest
        self.first
    end

    def self.newest
        self.last
    end

    def self.richest
        high_score = 0
        high_user = nil
        self.all.each do |user|
            if user.points > high_score
                high_score = user.points
                high_user = user
            end
        end
        high_user
    end

    def self.most_cards
        card_count = 0
        high_user = nil
        self.all.each do |user|
            if user.num_of_cards > card_count
                card_count = user.num_of_cards
                high_user = user
            end
        end
        high_user
    end

    def highest_card #returns highest card in a user's hand
        high_point = 0
        high_card = nil
        self.cards.each do |card|
            if card.points_worth > high_point
                high_point = card.points_worth
                high_card = card
            end
        end
        high_card
    end

    def points_from_highest_card
        self.highest_card.points_worth
    end

    def self.highest_card #returns user with the highest card in hand
        high_card = 0
        high_user = nil
        self.all.each do |user|
            user.cards.each do |card|
                if card.points_worth > high_card
                    high_card = card.points_worth
                    high_user = user
                end
            end
        end
        high_user
    end

    def hand_total
        self.cards.sum do |card|
            card.points_worth
        end
    end

    def self.highest_hand
        hand_count = 0
        high_user = nil
        self.all.each do |user|
            if user.hand_total > hand_count
                hand_count = user.hand_total
                high_user = user
            end
        end
        high_user
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:new, :create, :index]

    def index
        @top_users = User.top_five_users
        @oldest = User.oldest
        @newest = User.newest
        @richest = User.richest
        @biggest_hand = User.most_cards
        @highest_card_user = User.highest_card
        @highest_hand = User.highest_hand
    end
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        @user.points = 50
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Your account has been created. To get started, buy a box!"
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = current_user
    end

    def select_cards
        render :sell
    end

    def sell_cards
        params[:user][:cards_to_sell].each do |card_id|
            search_cards_and_remove(card_id)
        end
        flash[:notice] = "Sale successful. Congrats!"
        redirect_to user_path(current_user)
    end




    private

    def user_params
        params.require(:user).permit(:name, :password, :password_confirmation, :cards_to_sell => [])
    end

    def require_login
        if !session.include? :user_id
            flash[:alert] = "You must be logged in before viewing that page."
            redirect_to '/'
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Leaderboard</h1><br>
<div class=main_back>


<h2>Richest Player</h2>
<h3>Player with the most points</h3>
<% if @richest %>
    <table>
        <tr>
            <th>Name</th>
            <th>Points</th>
        </tr>
        <tr>
            <td><%=@richest.name%></td>
            <td><%=@richest.points%></td>
        </tr>
    </table>
<% else %>
<p>No Player Found!</p>
<% end %><br><br>

<h2>Highest Scoring Card</h2>
<h3>Player with the single card worth the most points</h3>
<% if @highest_card_user %>
    <table>
        <tr>
            <th>Name</th>
            <th>Card</th>
            <th>Points</th>
        </tr>
        <tr>
            <td><%=@highest_card_user.name%></td>
            <td><%=@highest_card_user.highest_card.name%></td>
            <td><%=@highest_card_user.points_from_highest_card%></td>
        </tr>
    </table>
<% else %>
<p>No Player Found!</p>
<% end %><br><br>

<h2>Highest Scoring Hand</h2>
<h3>Player with the most points in hand</h3>
<% if @highest_hand%>
<table>
    <tr>
        <th>Name</th>
        <th>Number of Cards</th>
        <th>Total Points in Hand</th>
    </tr>
    <tr>
        <td><%=@highest_hand.name%></td>
        <td><%=@highest_hand.num_of_cards%></td>
        <td><%=@highest_hand.hand_total%></td>
    </tr>
</table>
<% else %>
<p>No Player Found!</p>
<% end %><br><br>

<h2>Biggest Hand</h2>
<h3>Player with the most cards</h3>
<% if @biggest_hand%>
    <table>
        <tr>
            <th>Name</th>
            <th>Number of Cards</th>
        </tr>
        <tr>
            <td><%=@biggest_hand.name%></td>
            <td><%=@biggest_hand.num_of_cards%></td>
        </tr>
    </table>
<% else %>
<p>No Player Found!</p>
<% end %><br><br>

<h2>Oldest Player</h2>
<h3>Player who has been on Gem Trader the longest</h3>
<% if @oldest%>
    <table>
        <tr>
            <th>Name</th>
        </tr>
        <tr>
            <td><%=@oldest.name%></td>
        </tr>
    </table>
<% else %>
<p>No Player Found!</p>
<% end %><br><br>

<h2>Newest Player</h2>
<h3>Player who is newest to Gem Trader</h3>
<% if @newest%>
    <table>
        <tr>
            <th>Name</th>
        </tr>
        <tr>
            <td><%=@newest.name%></td>
        </tr>
    </table>
<% else %>
<p>No Player Found!</p>
<% end %><br><br>


<h2>High Scores</h2>
<table>
    <tr>
        <th>Position</th>
        <th>Name</th>
        <th>Points</th>
    </tr>
    <% count = 0 %>
    <% @top_users.each do |user| %>
    <% count += 1%>
    <tr>
        <td><%=count%></td>
        <td><%=user.name%></td>
        <td><%=user.points%></td>
    </tr>
    <% end %>
</table>
</div>

app/views/users/new.html.erb
<h1>Sign up for GemTrader!</h1>
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<% if @user.errors.any?%>
    <h2><%= pluralize(@user.errors.count, "error") %> holding you back from trading those gems:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>
<%= f.label :password%>
<%= f.password_field :password%><br>
<%= f.label :password_confirmation%>
<%= f.password_field :password_confirmation%><br>
<%= f.submit "Create Account"%>
<% end %><br><br>

Existing user? <%= link_to "Sign In", login_path %>

app/views/users/sell.html.erb
<h1>Gem Market</h1>
<div class=main_back>
<h2>Ready to sell? Select the cards you wish you sell below.</h2><br>
<% if current_user.cards.empty? %>
    Darn! You don't have any cards yet. Try buying a box first.<br>
<% else %>
    <%= form_tag '/sell_cards' do %>
    <%= collection_check_boxes(:user, :cards_to_sell, current_user.cards.order(:points_worth).order(:name), :id, :display_card) do |b| %>
    <%= b.label { b.check_box + b.text } %><br>
    <% end %>
    <%= submit_tag "Sell these Cards"%>

    <% end %>
<% end %><br><br>

<div class="buttons">
    <%= link_to "Nevermind, don't sell", user_path(current_user)%><br>
</div>
<br>

</div>

app/views/users/show.html.erb
<div class=main_back>
<h1>Welcome, <%= @user.name%>!</h1>
<h2>Points: <%=current_user.points%></h2>
<% flash.each do |type, msg| %>
    <div>
        <%= msg %>
    </div>
<% end %><br><br>
<div class="buttons">
    <div id="middle">
        <%=link_to "Sell Cards", '/sell_cards'%>
        <%=link_to "Buy a Box of Cards", boxes_path%>
        </div>
</div><br><br><br><br>
<h2>Your Cards</h2><br>
    <% if current_user.cards.empty? %>
    <p>No Cards! Time to buy another box.</p>
    <% end %>
    <% current_user.cards.each do |card|%>
    <div class="gem">
        <h6><%= card.name %></h6>
        <p><%= card.points_worth %> pts</p>
    </div>
    <% end %><br>

<br><br>
</div>