config/routes.rb
Rails.application.routes.draw do
  resources :boxes, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :show]
  get '/', to: 'welcome#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/sell_cards', to: 'users#select_cards'
  post '/sell_cards', to: 'users#sell_cards'
end

app/models/box.rb
class Box < ApplicationRecord
    has_many :box_cards
    has_many :cards, through: :box_cards

    def cards_at_least_50
        card_arr = []
        until points_total_of_box(card_arr) >= 50
            card_arr = box_populate
        end
        card_arr
    end
    
    def box_populate
        arr = []
        self.cards.map do |card|
            if card_point_range_for_common?(card)
                10.times do
                    arr << card
                end
            elsif card_point_range_for_uncommon?(card)
                10.times do
                    arr << card
                end
            elsif card_point_range_for_rare?(card)
                4.times do
                    arr << card
                end
            end
            arr << card
        end
        arr.sample(3)
    end

    def card_point_range_for_common?(certain_card)
        !!certain_card.points_worth.between?(5,25) && self.rarity == "Common"
    end

    def card_point_range_for_uncommon?(certain_card)
        !!certain_card.points_worth.between?(5,150) && self.rarity == "Uncommon"
    end

    def card_point_range_for_rare?(certain_card)
        !!certain_card.points_worth.between?(151,1000) && self.rarity == "Rare"
    end

    def points_total_of_box(array)
        total = 0
        array.each do |card|
            total += card.points_worth
        end
        total
    end

    def enough_points?(user_points)
        if user_points >= self.cost
            return true
        else
            return false
        end
    end


end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
    before_action :require_login

    def index
        @boxes = Box.all
    end

    def show
        @box = Box.find(params[:id])
        @box_cards = @box.cards_at_least_50
        if @box.enough_points?(current_user.points)
            current_user.cards << @box_cards
            current_user.update(points: current_user.points - @box.cost)
        else
            flash[:alert] = "That box was out of your budget."
            return redirect_to user_path(current_user)
        end
    end

    private 
    def require_login
        if !session.include? :user_id
            flash[:message] = "You must be logged in before viewing that page."
            redirect_to '/'
        end
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/index.html.erb
<h1>Pick a Box</h1>
<div class=main_back>

<h2>Points: <%=current_user.points%></h2>

<% @boxes.each do |box| %>
    <div class=boxes>
        <%= link_to "#{box.rarity} Cost: #{box.cost} " , box_path(box)%>
    </div>
    <% end %>

    <br>
    <br>
    <br>


<h3>Gem Cards Availible</h3>
<% @boxes.first.cards.each do |card| %>
    <div class="gem">
        <h6><%= card.name %></h6>
        <p><%= card.points_worth %> pts</p>
    </div>
<% end %>

app/views/boxes/show.html.erb
<%= @box.rarity %><br>

<% @box_cards.each do |card| %>
    <div class="gem">
        <h6><%= card.name %></h6>
        <p><%= card.points_worth %> pts</p>
    </div>
<% end %>
<div class="space"></div>
<%= link_to "Return to Profile", user_path(current_user) %>