config/routes.rb
Rails.application.routes.draw do
  resources :boxes, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :show]
  get '/', to: 'welcome#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/sell_cards', to: 'users#select_cards'
  post '/sell_cards', to: 'users#sell_cards'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GemTraderApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="buttons">
    <%if current_user %>
      <%= link_to "Home", user_path(current_user), class: "left"%>
    <% else %>
      <%= link_to "Home", '/', class: "left"%>
    <% end %>

    <%= link_to "High Scores", users_path, class: "left"%>

        <%if current_user %>
      <%= link_to "Logout", logout_path, method: "post", class: "right"%>
    <% else %>
      <%= link_to "Login", login_path, class: "right"%>
    <% end %>
  </div>

  <h1 id="logo"><%= image_tag 'gt_logo.png' %></h1>
    <%= yield %>
  </body>
</html>